examples/minibrowser/build.gradle
wpe/build.gradle

This is a precursory change for the AHardwareBuffer-based approach to
buffer management.

Bump minimum SDK version to 26

---

wpe/src/main/glue/browser/browser.cpp

Don't use a higher priority than that since it can drain out other
frequently-dispatched sources that use the default priority.

Handle touch events at G_PRIORITY_DEFAULT priority

---

wpe/CMakeLists.txt
wpe/src/main/glue/browser/entrypoints.cpp
wpe/src/main/glue/browser/looperthread.cpp
wpe/src/main/glue/browser/looperthread.h
wpe/src/main/java/com/wpe/wpe/Browser.java
wpe/src/main/java/com/wpe/wpe/BrowserGlue.java

Along with the rest of the Browser glue, also initialize a dedicated thread
that will be spun by an ALooper object and the underlying Java-based Looper.
This will allow leveraging native APIs like AChoreographer which aren't able
to operate on any thread that's not run by a Looper.

Add a Looper-based helper thread

---

scripts/patch.py

```
Traceback (most recent call last):
File "/home/mortimer/Projects/wpe-android/./scripts/patch.py", line 100, in <module>
Patch(sys.argv[1], sys.argv[2]).run()
File "/home/mortimer/Projects/wpe-android/./scripts/patch.py", line 93, in run
Bootstrap(self.__arch, False).install_deps(sysroot, self.__get_install_list())
TypeError: __init__() takes 2 positional arguments but 3 were given
```

Fix patch.py script error

---

wpe/src/main/glue/browser/renderer_asurfacetransaction.cpp
wpe/src/main/glue/browser/renderer_asurfacetransaction.h
wpe/src/main/java/com/wpe/wpe/BrowserGlue.java
wpe/src/main/java/com/wpe/wpe/gfx/View.java

* Adds the necessary entrypoint, invokes it from SurfaceHolder
* Fixes RendererASurfaceTransaction to properly handle and execute surface redraw requests coming from gfx.View
* Sprinkles comments inside the RendererASurfaceTransaction class to provide more insight into its behavior.

RendererASurfaceTransaction redraw fixes

---

wpe/src/main/java/com/wpe/wpe/Page.java
wpe/src/main/java/com/wpe/wpe/gfx/View.java
wpe/src/main/java/com/wpe/wpeview/SurfaceClient.java
wpe/src/main/java/com/wpe/wpeview/WPEView.java
wpe/src/main/java/com/wpe/wpeview/WPEViewClient.java

SurfaClient delegate allows host application to inject custom surfaces where WPEView renders it's contents to. For example this is used in VR in order to straight render to a swapChain surface instead of using the SurfaceHolder from the SurfaceView

Add SurfaceClient API

---

wpe/src/main/java/com/wpe/wpe/Browser.java

There are some methods in Browser.java that don't perform page existence checks, which leads to some NullPointerException crashes if related APIs are called after WPEView is detached from window (or before attaching)

Check that page exists before calling methods

---

wpe/src/main/java/com/wpe/wpe/services/ServiceUtils.java

Fixes crash related to fontconfig:
2021-07-09 12:48:22.400 23795-23839/com.wpe.examples.minibrowser D/wpe-android: Fontconfig error: 
2021-07-09 12:48:22.400 23795-23839/com.wpe.examples.minibrowser D/wpe-android: Cannot load default config file: No such file: (null)
2021-07-09 12:48:22.400 23795-23839/com.wpe.examples.minibrowser D/wpe-android: --------- beginning of crash

Make sure folders are correctly created in ServiceUtils.copyFile

---

.github/workflows/build.yml
scripts/bootstrap.py

This adds configuration for GitHub actions to build the project on PRs and store the resulting Minibrowser APKs as artifacts.
For now the build uses prebuilt bootsrap packages—figuring out how to automate building those would be a different task 😉

CI: Add GitHub actions configuration

---

scripts/bootstrap.py

While the latest stable in the series is 2.34.6, there was already some work in the [Cerbero repository](https://github.com/Igalia/cerbero/) to get WebKit updated to 2.34.1 and it seemed better to complete that as a stepping stone before doing further updates 😉 
Prebuilts were already uploaded last week to https://wpewebkit.org/android/bootstrap/2.34.1/ (which is the new location used by the script after #52 was merged), produced from https://github.com/Igalia/cerbero/commit/a8625e4daba83da20f0841d528e657c0c180d43b
I did some smoke testing on a device running Android 11 and the Minibrowser is working as expected.

Bump WPE WebKit to 2.34.1

---

scripts/bootstrap.py

SSIA.
I have uploaded fresh packages to https://wpewebkit.org/android/bootstrap/2.34.6/ as well. Version `2.34.6-20220329A` includes also the changes from https://github.com/Igalia/cerbero/pull/11 so I suppose @zhani may want this PR merged before #57 😉

Bump WPE WebKit to 2.34.6

---

wpe/src/main/glue/browser/entrypoints.cpp
wpe/src/main/glue/networkprocess/entrypoints.cpp
wpe/src/main/glue/webprocess/entrypoints.cpp

VM resolves and calls JNI_OnLoad from loaded library. libWPEWebKit has dependency
to libgstreamer.so which also exports JNI_OnLoad. JNI_OnLoad in libgstreamer requires
GStreamer java class to be present in specific package and call fails with invalid JNI
version if GStreamer java class is not found. By declaring JNI_OnLoad in glue code we prevent
JNI_OnLoad in libgstreamer.so from being called as for now we don't need GStreamer Java bindings.
Fixes #64

Implement JNI_Onload in glue code

---

.gitignore
build.gradle
scripts/bootstrap.py

- change shebang to correctly call python3 on old systems which are
using python2 as default
- force using LC_ALL=C when calling readelf in order to have regex
working on non-english systems

Improve bootstrap.py script compatibility

---

wpe/CMakeLists.txt
wpe/src/main/glue/browser/entrypoints.cpp
wpe/src/main/glue/common/jnihelper.cpp
wpe/src/main/glue/common/jnihelper.h
wpe/src/main/glue/networkprocess/entrypoints.cpp
wpe/src/main/glue/webprocess/entrypoints.cpp

- Also do proper casts that are required for emulator to work
- Change JNI version to 1.6
- Use weak global ref when storing peer value because jenv and
jobject refs are only valid during the call
Depends on https://github.com/Igalia/cerbero/pull/13
Required for #13

Implement process spawn hooks in Android layer

---

.github/workflows/build.yml
README.md
examples/minibrowser/build.gradle
scripts/bootstrap.py
wpe/build.gradle

Assuming that Cerbero has already been successfully used to build ARMv7 bootstrap packages:
```sh
./scripts/bootstrap.py -a armv7 -c ../cerbero
```

Enable builds targeting armv7

---

docs/development.md
tools/minibrowser/README.md
tools/minibrowser/src/main/java/com/wpe/tools/minibrowser/Browser.kt
wpe/src/main/cpp/browser/browser.cpp
wpe/src/main/cpp/browser/browser.h
wpe/src/main/cpp/browser/entrypoints.cpp
wpe/src/main/cpp/browser/page.cpp
wpe/src/main/cpp/browser/page.h
wpe/src/main/cpp/browser/pageeventobserver.cpp
wpe/src/main/cpp/browser/pageeventobserver.h
wpe/src/main/cpp/browser/renderer.h
wpe/src/main/cpp/browser/renderer_asurfacetransaction.cpp
wpe/src/main/cpp/browser/renderer_asurfacetransaction.h
wpe/src/main/cpp/browser/renderer_fallback.h
wpe/src/main/java/com/wpe/wpe/Browser.java
wpe/src/main/java/com/wpe/wpe/BrowserGlue.java
wpe/src/main/java/com/wpe/wpe/Page.java
wpe/src/main/java/com/wpe/wpe/gfx/ViewObserver.java
wpe/src/main/java/com/wpe/wpe/gfx/WPESurfaceView.java
wpe/src/main/java/com/wpe/wpe/gfx/WPESurfaceViewObserver.java
wpe/src/main/java/com/wpe/wpeview/WPEView.java
wpe/src/main/java/com/wpe/wpeview/WebChromeClient.java

This version is trivial version of fullscreen support. This puts API in place but implementation will be improved later on along with graphics stack and other feature improvements.
- Implements fullscreen support and API similar to Android WebView
- Renames com.wpe.wpe.gfx.View to com.wpe.wpe.gfx.WPESurfaceView to avoid confusion with android.view.View
Fixes #1 
Depends on https://github.com/Igalia/cerbero/pull/18

Introduce initial version of fullscreen support

---

tools/minibrowser/src/main/java/com/wpe/tools/minibrowser/Browser.kt

By mistake minibrowser called hide fullscreen immediately
when fullscreen was shown.
Patch also fixes some Kotlin convetion issue by removing
redundant semicolons

Fix bug in minibrowser fullscreen handling

---

tools/scripts/bootstrap.py

Rename `libWPEBackend-android.so` into `libWPEBackend-default.so` in order to avoid using a symlink. There is no need to include the file in the generated packages with the `libWPEBackend-android.so` name, so this change is harmless and sidesteps some potential failure modes (symlinks
not supported at build time, dynamic linker rejecting symlinks, etc.)

bootstrap: Avoid using a symlink for the backend library

---

tools/minibrowser/src/main/java/com/wpe/tools/minibrowser/Browser.kt
wpe/src/main/java/com/wpe/wpeview/WPEChromeClient.java
wpe/src/main/java/com/wpe/wpeview/WPEView.java

Renaming to avoid confusion with Android system webview API WebChromeClient

Rename WebChromeClient to WPEChromeClient

---

tools/minibrowser/src/main/res/layout/activity_main.xml

Align bottom makes address/toolbar more usable on device and
is according to current layout styles

Align minibrowser address/toolbar to bottom

---

wpe/src/main/cpp/Browser/Browser.cpp
wpe/src/main/cpp/Browser/Browser.h
wpe/src/main/cpp/Browser/EntryPoints.cpp
wpe/src/main/cpp/Browser/Page.cpp
wpe/src/main/cpp/Browser/Page.h
wpe/src/main/cpp/Browser/RendererASurfaceTransaction.cpp
wpe/src/main/java/com/wpe/wpe/Browser.java
wpe/src/main/java/com/wpe/wpe/BrowserGlue.java
wpe/src/main/java/com/wpe/wpe/Page.java

This is done in preparation to match WPEView API with Android system webview API. Android system webview considers similar entities as app wide instances.
This commit also changes Browser::getInstance() to Browser::instance() according to webkit code style
"Precede setters with the word “set”. Use bare words for getters"

Move webkit context and datamanager to browser singleton

---

wpe/src/main/java/com/wpe/wpe/Browser.java
wpe/src/main/java/com/wpe/wpe/services/WPEService.java
wpe/src/main/java/com/wpe/wpe/services/WPEServiceConnection.java
wpe/src/main/java/com/wpe/wpe/services/WPEServiceConnectionDelegate.java

In some cases WebProcess and NetworkProcess call exit(0) directly and in such cases Android tries to restart bound service. This is wrong because it's not Android system that should restart auxiliary processes but WebKit.
Fixes #138 138

Do not restart service in case of crash or auxiliary process direct exit

---

wpe/src/main/java/com/wpe/wpeview/WPEView.java

onDetachedFromWindow call can happen when fragment is changed. For example going from webpage to browser settings. This should not destroy underlying webkit page instance.

Do not destroy WebKit view on onDetachedFromWindow call

---

wpe/src/main/aidl/com/wpe/wpe/IWPEService.aidl
wpe/src/main/aidl/com/wpe/wpe/IWPEServiceHost.aidl
wpe/src/main/cpp/Browser/Page.cpp
wpe/src/main/cpp/Browser/Page.h
wpe/src/main/cpp/Browser/RendererASurfaceTransaction.cpp
wpe/src/main/cpp/Browser/RendererASurfaceTransaction.h
wpe/src/main/java/com/wpe/wpe/Browser.java
wpe/src/main/java/com/wpe/wpe/services/WPEService.java
wpe/src/main/java/com/wpe/wpe/services/WPEServiceConnection.java

In general add better handling of clean exits and crashed exits.
This patch includes following features/fixes:
- Added new ipc callback to deal with clean exits before android considers them as crash
- Thread safe callbacks pushed to main thread if needed
- Proper destruction of wpe interface
- SurfaceTransaction fixes to deal with crashed webprocess

Do not crash on webpage close

---

tools/mediaplayer/build.gradle
wpe/src/main/cpp/Browser/Page.cpp
wpe/src/main/cpp/Browser/Page.h
wpe/src/main/java/com/wpe/wpe/Page.java

Depends on [[wpewebkit] Remove hardcoded device scale patch](https://github.com/Igalia/wpe-android-cerbero/pull/46)

[wpe] Fix device scale according Android DisplayMetrics

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
tools/scripts/check-format.py

- upgrade the gradle wrapper version
- allow using venv with python scripts

Fix build on Ubuntu Noble

---

tools/scripts/bootstrap.py
wpeview/src/main/java/org/wpewebkit/wpe/WKRuntime.java

wpewebkit 2.46.3 includes many of the patches that were added on top of 2.46.0 for Android. Those can be now dropped from cerbero build. 2.46.3 also includes renaming from WPEMonitor to WPEScreen which matches better to Android for new platform API.
Note! Before merging this:
- [] https://github.com/Igalia/wpe-android-cerbero/pull/48 must be merged first
- [] https://github.com/Igalia/wpe-android-cerbero/pull/48 must be built and deployed by CI first
Fixes #174

[wpe] Upgrade to wpewebkit 2.46.3

---

.github/workflows/build.yml
.github/workflows/check.yml
.github/workflows/lint.yml
.github/workflows/publish-to-maven-central.yml

The setup-android action takes care of making sure that the Android SDK is installed in the desired version, and let the gradlew wrappers fetch Gradle as-needed (which is the recommended anyway). This makes workflows work with [Act][act], allowing running and debugging them locally.
[act]: https://github.com/nektos/act

CI: Replace the setup-gradle action with setup-android

---

.github/workflows/build.yml
.github/workflows/check.yml
.github/workflows/lint.yml
build.gradle
tools/mediaplayer/src/main/AndroidManifest.xml
tools/mediaplayer/src/main/java/org/wpewebkit/tools/mediaplayer/MainActivity.java
tools/minibrowser/build.gradle
tools/webdriver/build.gradle
wpeview/build.gradle
wpeview/src/androidTest/AndroidManifest.xml
wpeview/src/main/AndroidManifest.xml

Replace deprecated function usages from build.gradle files.
Also includes:
- Upgrade AGP to more recent version
- Upgrade library dependencies to more recent versions
- Upgrade Android cmd line tools version used by CI workflows
- Add separate AndroidManifest.xml for tests
- Fix lint errors
#178

build: Replace deprecated function usages

---

wpeview/src/main/cpp/Runtime/RendererSurfaceControl.cpp
wpeview/src/main/cpp/Runtime/ScopedWPEAndroidBuffer.h

It's not guaranteed that RendererSurfaceControl receives previous frame release fd. This patch adds check if fd is valid before trying to use it.
AHardwareBuffer usage and recycling logic is not robust and needs more fixing. But it's better to fix it alongside the adoption of new platform API.
Fixes #137

[wpeview] Fix crash on RendererSurfaceControl FD release

---

tools/mediaplayer/lint.xml
wpeview/lint.xml

Change the severity of the `AndroidGradlePluginVersion`, `NewerVersionAvailable`, and `GradleDependency` lint checks to warnings, to avoid detection of newer versions from stopping the CI.

lint: Treat new package version checks as warnings

---

wpeview/src/main/cpp/Service/EntryPoint.cpp

Use the C++ mangled named for the `WebKit::WebProcessMain()` and `WebKit::NetworkProcessMain()` functions, instead of the ones with the `android_` prefix.
This will allow dropping a patch on top of vanilla WPE WebKit that added the `android_WebProcess_main()` and `android_NetworkProcess_main()` symbols. The only additional thing those wrappers did was sending the list of arguments to the Android log, for debugging purposes, but that may be re-added at a later time inside `initializeNativeMain()` without needing to modify WPE WebKit.

[wpeview] Use mangled C++ names for entrypoints

---

tools/scripts/webkitpy/requirements.txt

Add the missing `urllib3` dependency to the list of requirements needed to run Selenium and W3C tests. This should fix errors like the following:
https://github.com/Igalia/wpe-android/actions/runs/14041836539/job/39334480607#step:9:16

webdriver: Add missing urllib3 dependency

---

gradle/libs.versions.toml
tools/minibrowser/src/main/java/org/wpewebkit/tools/minibrowser/BrowserFragment.kt
tools/minibrowser/src/main/java/org/wpewebkit/tools/minibrowser/MainActivity.kt

Add an insets listener to apply the system bar insets to the browser main view, ensuring that the main view will not cover the bars. While at it, opt-in to edge-to-edge mode explicitly to ensure the same behaviour also on older Android releases.
In Android 15 applications targeting SDK 35 are opted in to edge-to-edge mode, which makes applications cover as much of the screen as possible but may result in undesired overlaps if unhandled. For now the handling is as simple as possible to get the existing behaviour back.
Fixes #189

[minibrowser] Apply system bar insets to main view

---

tools/scripts/bootstrap.py
wpeview/src/main/java/org/wpewebkit/wpe/WKRuntime.java

This will be the last update in the series before moving over to the 2.48.x ones.
The corresponding Cerbero update was done in https://github.com/Igalia/wpe-android-cerbero/pull/56

[wpe] Upgrade to WPE WebKit 2.46.7

---

tools/minibrowser/src/main/java/org/wpewebkit/tools/minibrowser/BrowserFragment.kt

Check whether IME is visible (i.e. the on screen keyboard) and take it into account when applying insets to the main browser fragment. Previously only the system bars insets were taken into account, which resulted in the IME covering the toolbar and part of the web view.
Fixes #192

[minibrowser] Take into account IME insets

---

wpeview/src/main/cpp/Service/EntryPoint.cpp

https://github.com/Igalia/wpe-android/blob/b918e3f8b86eda406436cb251c2e7b10a529008c/wpeview/src/main/cpp/Service/EntryPoint.cpp#L55 describes the expected mangled names for the various entry points.
After https://commits.webkit.org/293601@main, the entry point was intended to change into `WebKit::WebDriverProcessMain` (but it didn't because it was using an undeclared namespace)
This PR needs a corresponding WebKit upstream one that I'll link shortly

[wpe] Update entry point name for WebDriverProcess

---

tools/minibrowser/src/main/res/values-night/themes.xml

Dark mode was missing custom layout for preferences and thus it crashes. This patch adds custom preferences theme and layout for dark mode theme.
Fixes #198

[minibrowser] Set custom preferences theme layout for dark mode

---

tools/scripts/bootstrap.py
wpeview/src/main/java/org/wpewebkit/wpe/WKRuntime.java
wpeview/src/main/java/org/wpewebkit/wpe/services/NetworkProcessService.java
wpeview/src/main/java/org/wpewebkit/wpe/services/WebDriverProcessService.java
wpeview/src/main/java/org/wpewebkit/wpe/services/WebProcessService.java

Web Inspector resources now being shipped as a `.gresource` file instead of a shared library, which needed changes in the bootstrap script and setting the relevant environment variable. For now the `.gresource` file is installed along the injected bundle, as the shared library was previously, but this may change in the future.
----
~~Note this is expected to fail CI until bootstrap packages for the corresponding release are available.~~ Bootstrap packages for 2.48.2 are now available 😄

[wpe] Update to WPE WebKit 2.48.2

---

tools/minibrowser/src/main/java/org/wpewebkit/tools/minibrowser/BrowserFragment.kt
tools/minibrowser/src/main/java/org/wpewebkit/tools/minibrowser/Utils.kt
tools/minibrowser/src/main/java/org/wpewebkit/tools/minibrowser/settings/SettingsFragment.kt
tools/minibrowser/src/main/java/org/wpewebkit/tools/minibrowser/settings/clearbrowsingdata/ClearBrowsingDataFragment.kt

Apply “standard” insets (IME + system toolbars) to the Minibrowser settings views. While at it, factor out the code into a `View` extension method which gets reused by all the views that needs to have insets applied.
Also, make sure that the insets are applied even if a `View` is not yet attached. This is achieved by installing an `OnAttachStateChangeListener` when the View is not yet attached, which then requests application and removes itself afterwards.
----
Fixes #199

[minibrowser] Apply standard insets to settings views

---

wpeview/src/main/java/org/wpewebkit/wpe/WKWebView.java

There is a call onInputMethodContextOut() to hide IME when page loading starts. This is a workaround because WebKit didn't properly handle IME in this case. However, it has been fixed in WebKit by https://bugs.webkit.org/show_bug.cgi?id=273387. Thus this call can be removed.

[wpe] Remove unnecessary onInputMethodContextOut() call

---

tools/scripts/bootstrap.py
wpeview/src/main/java/org/wpewebkit/wpe/WKRuntime.java
wpeview/src/main/java/org/wpewebkit/wpe/services/NetworkProcessService.java
wpeview/src/main/java/org/wpewebkit/wpe/services/WebDriverProcessService.java
wpeview/src/main/java/org/wpewebkit/wpe/services/WebProcessService.java

This is a minor bugfix release, changing the versions strings is enough.
----
Note that the CI build will fail until https://github.com/Igalia/wpe-android-cerbero/pull/68 is merged and updated bootstrap tarball packages uploaded.

[wpe] Update to WPE WebKit 2.48.3

---

wpeview/src/main/java/org/wpewebkit/wpe/WKRuntime.java

WebKit's ProcessLauncher::launchProcess, in ProcessLauncherGLib.cpp, keeps full ownership of the socket pair's client file descript as it shares it into LibWPE's launchProcess.
wpe-android assumed transferred ownership, and used ParcelFileDescriptor.adoptFd for the incoming file descriptor, which resulting in fdsan aborting when the WebKit side closed.
This changes it to use ParcelFileDescriptor.fromFd, which in turn duplicates the descriptor.
As a workaround for this fdsan problem, we used a patch in wpe-android-cerbero that reverted using RAII file descriptors in WebKit, something that effectively resulted in the fd being transferred over. Landing this in wpe-android requires removing the patch in wpe-android-cerbero.

WKRuntime: Use ParcelFileDescriptor.fromFd

---

tools/scripts/bootstrap.py
wpeview/src/main/cpp/CMakeLists.txt
wpeview/src/main/cpp/Common/Init.cpp
wpeview/src/main/cpp/Common/Init.h
wpeview/src/main/cpp/Runtime/EntryPoint.cpp
wpeview/src/main/cpp/Service/EntryPoint.cpp
wpeview/src/main/java/org/wpewebkit/wpe/WKRuntime.java
wpeview/src/main/java/org/wpewebkit/wpe/WKVersions.java
wpeview/src/main/java/org/wpewebkit/wpe/services/NetworkProcessService.java
wpeview/src/main/java/org/wpewebkit/wpe/services/WebDriverProcessService.java
wpeview/src/main/java/org/wpewebkit/wpe/services/WebProcessService.java

This adds a new `WKVersions` Java class which contains static constants for the WPE WebKit and GStreamer versions being used at run time. The values are filled early during the `JNI_OnLoad` implementation, in common code used both by the runtime (UI) and service (helper processes) entry points, which allows using the values from any of the other Java classes.
The first usage of the new functionality is calculating at runtime the versioned strings used to identify unpacked assets for each of the processes. This avoids the need to manually update those, which is easy to forget.
In the future this could also be used for other purposes, e.g. the MiniBrowser could show the versions in its settings activity for error reporting and debugging purposes.

Expose WPE WebKit and GStreamer versions to Java
